### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Manliketjb** [qbcore-framework/qb-bankrobbery#55]
[  script:qb-doorlock] SCRIPT ERROR: @qb-doorlock/server/main.lua:6: attempt to index a nil value (field '?')

when going near the Paleto bank

new install

**Comment by vulthrax** [comment]
Hi, i had this problem too i have a work around to get rid of it. You probably deleted doors in qb-doorlock. For some reason the script gets this error from the moment you delete doors also doors that arent used in the robbery script are generating this bug. I only use qb-doorlock for the banks because its needed to make the banks work, in the config file there is a line that says keep all coordinates  or banks wont work. I can confirm it are more banks that you cant remove or it fails. 

How did i get rid of this bug? Its not the best way but its wa workaround: 

1. I redownloaded the config file of qb-doorlock. 
2. Then i copied all original doors back in to the config of the file i'm using. 
3. I deleted every door one by one from the ones i dont use to see if they generate a bug while being in the palleto bank.
(almost all doorlocks are needed but i managed to get rid of a few of them mostly the ones at the bottom of the default config script)
4. Then here is a problem: If you are using a custom MLO for let say police interiors. Your gonna have doors that are in the way and visible because they are there for the original interior. to solve this i just added in the height of the coordinates (last digits in the coordinate) of each door a -1 in front of the coords. so the doors spawn under the map like 100 spaces lower as they were intended. 
5. After doing this there will be no errors when inside the pallleto bank.

**Comment by Manliketjb** [comment]
better than my solutions... I just deleted qb-bankrobbery and qb-doorlock to switch it with better robberies as doorlocks.

nothing working in fixing it, I can have the default qb-doorlock and still get the errors, the bankrobbery would work so much better if it didn't reply on another script to to make the door function. pretty sure that is why so many robbery scripts have the door controls built in to the robbery script its self
