### ISSUE TITLE
Electronickit

### ISSUE THREAD

**Issue by GhostLegionRP** [qbcore-framework/qb-bankrobbery#74]
Can't use Electronickit on each Bank.

When i try to use it, I didn't get the minigame.

**Comment by Brianelvio** [comment]
@GhzGarage @GhostLegionRP 
This issue is very easily fixed by changing the following in [server] main.lua

`QBCore.Functions.CreateUseableItem("electronickit", function(source)
    local Player = QBCore.Functions.GetPlayer(source)
    if not Player or Player.Functions.GetItemByName('electronickit') then return end
    TriggerClientEvent("electronickit:UseElectronickit", source)
end)`

To

`QBCore.Functions.CreateUseableItem("electronickit", function(source)
    local Player = QBCore.Functions.GetPlayer(source)
    if not Player or not Player.Functions.GetItemByName('electronickit') then return end
    TriggerClientEvent("electronickit:UseElectronickit", source)
end)`

The if statement checking for player and item was missing a not logical operator.

**Comment by GhostLegionRP** [comment]
> 

the statement was this

QBCore.Functions.CreateUseableItem("electronickit", function(source)
    local Player = QBCore.Functions.GetPlayer(source)
    if not Player or not Player.Functions.GetItemByName('electronickit') then return end
    TriggerClientEvent("electronickit:UseElectronickit", source)
end)

it's the same statement where you send since the update but it won't work.

**Comment by GhostLegionRP** [comment]
> I got fixed this by restarting the script on server.cfg, just add `restart qb-bankrobbery` after all the ensure statements

Yep thats it

**Comment by sandunisuru** [comment]
@GhostLegionRP Do you have Osmium OP's ATM Robbery in your server that uses Elecronickit as robbery activator.

**Comment by GhostLegionRP** [comment]
> @GhostLegionRP Do you have Osmium OP's ATM Robbery in your server that uses Elecronickit as robbery activator.

Yes i have why ?

**Comment by sandunisuru** [comment]
I think that may be the issue. Both have Electronickit as usable item and when you use the Electronickit it will take ATM Robbery event instead of Bank Robbery event. You have two methods to fix,
1) Change usable item on ATM Robbery or Bank Robbery
2) Change interaction to something like qb-target for ATM Robbery or Bank Robbery.

**Comment by GhostLegionRP** [comment]
> I think that may be the issue. Both have Electronickit as usable item and when you use the Electronickit it will take ATM Robbery event instead of Bank Robbery event. You have two methods to fix,
> 1) Change usable item on ATM Robbery or Bank Robbery
> 2) Change interaction to something like qb-target for ATM Robbery or Bank Robbery.
> 

I have replaced item in ATM now it works fine without restart

**Comment by BerkieBb** [comment]
This was already fixed
